import { Inter } from "@next/font/google";
import type { Metadata } from "next";
import { twMerge } from "tailwind-merge";

import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Modsen Client Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const bodyClass = twMerge(
    `antialiased flex flex-col justify-center`,
    inter.className,
  );
  return (
    <html lang="en">
      <body className={bodyClass}>
        <Header />
        <div className="w-full">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
