import { Inter } from "@next/font/google";
import type { Metadata } from "next";

import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";

import "./globals.css";

export const metadata: Metadata = {
  title: "Modsen Client Blog",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased flex flex-col justify-center ${inter.className}`}
      >
        <Header />
        <div className="w-full">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
